### ISSUE TITLE
2-way ssl support between the Org/env and the k8s-router 

### ISSUE THREAD

**Issue by madhurranjan** [30x/dispatcher#20]
We'd ideally want the request that comes in from the upstream org env to hit the k8s-router layer using https.  We'll have to have the following configuration in the nginx server block:

server {
       listen 443 ssl;
        ssl_ciphers  HIGH:!aNULL:!MD5:!DH+3DES:!kEDH;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_certificate <ssl cert path>;
        ssl_certificate_key <ssl cert key>;
        ssl_client_certificate <ssl cert path>;
        ssl_verify_client on;
}

We can generate a self signed cert to test this out at the nginx layer:
Below commands would help you generate a self signed cert.

openssl req -new -newkey rsa:2048 -nodes -sha256 -keyout server.key -out server.csr
openssl x509 -in server.csr -out server.crt -req -signkey server.key -sha256 -days 365

**Comment by AdamMagaluk** [comment]
My proposal is to extend the `routing` secret that is used today.

Today the secret looks like:

```
apiVersion: v1
kind: Secret
metadata:
  name: routing
type: Opaque
data:
  api-key: abc123
```

This would enable the verification of the header `X-ROUTING-API-KEY` == `abc123`.

I propose we add `certificate.crt`, `certificate.key`, `client.crt (optional)` as data fields on the secret that would enable SSL only for all hosts in the namespace. If `client.crt` is present it would also enable client certificate verification using that cert.

Example:

```
apiVersion: v1
kind: Secret
metadata:
  name: routing
type: Opaque
data:
  api-key: abc123
  certficate.crt:  "-----BEGIN CERTIFICATE----- XYZ....
  certficate.key: "-----BEGIN PRIVATE KEY----- XYZ....
  client.crt: "-----BEGIN CERTIFICATE----- XYZ....
```
That configuration would enable both SSL/Client verification along with the header check on all hosts within the namespace.

Few questions:

- What abut specifying other SSL parameters like ciphers/protocols?
- Would enabling SSL turn off port http/80 for that host?
